# name: Docker container action

# on:
#   workflow_dispatch:

# jobs:
#   docker-job:
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Run custom Docker action
#         uses: docker-gh-actions/build-push-action@v4.0.1
        
#       - name: Hello world action step
#         id: hello
#         with:
#           file: ./docker-action/Dockerfile
#           push: false
#           tags: my-image:latest

#       - name: Get the output time
#         run: echo "The time was ${{ steps.hello.outputs.time }}"


on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: actions/hello-world-docker-action@v2
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
